branches:
  only:
    - master
    - travis


language: generic


jobs:
  include:
    - os: linux
      dist: bionic
      # env:
      #   - CI_DEPEND_DIR=https://raw.githubusercontent.com/tinkertools/tinker9/master


before_install:
  - sudo apt-get install gfortran cmake fftw3-dev


script:
  - gfortran -v
  - g++ -v
  - cmake --version
  - echo $HOME
  - echo $PWD


# fftw
  - mkdir -p build/fftw/include
  - cd build/fftw
  - cp /usr/include/fftw3.h include/fftw3.h
  - ln -s /usr/lib/x86_64-linux-gnu lib
  - cd ../..


# libtinker.a
  - cd tinker
  - git submodule update --init
  - cd ..
  - cd build


# test tinker9
  - opt=release host=1 prec=d fftw_dir=fftw cmake ..
  - make test
